# -*- coding: utf-8 -*-
"""Chitkara MBA HR AI_Driven_India_Level_Decision_Intelligence_System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CywptKJ9Adwo-t9D17AqkknSVz5Tv_rE

##AI-Driven Decision Intelligence System – Concept Explanation

##Organization text

This project is designed for a hypothetical company, BharatMart Analytics Pvt. Ltd., a pan-India retail and logistics organization operating across multiple states. The company deals with large volumes of data generated from sales transactions, customer interactions, marketing campaigns, and inventory operations.

Despite having access to this data, the organization faces challenges in deriving meaningful, region-specific insights. Decision-making is largely based on aggregated reports, which do not capture state-level variations in performance, demand, and customer behavior.

System Objective

The system is developed to transform raw business data into actionable insights by integrating machine learning models with a structured analytical workflow. It enables the organization to:

Understand business performance at a state level

Predict future outcomes such as revenue and demand

Identify customer risk segments

Support data-driven decision-making across functions

Role of Google Colab in the System

Google Colab serves as the analytical backbone of the system. It performs the following functions:


1. Data Processing

The system begins by loading and cleaning the dataset. This includes handling missing values, removing inconsistencies, and structuring the data for analysis. Derived variables such as revenue and performance indicators are created to represent real business scenarios.


2. Predictive Modeling

Two types of machine learning models are implemented:


a. Regression Model (Revenue Prediction)

A regression model is used to predict future revenue based on factors such as units sold, pricing, marketing spend, and customer activity. This enables the organization to forecast demand and plan inventory and financial strategies accordingly.


b. Classification Model (Customer Risk Prediction)

A classification model is used to categorize customers into risk segments, such as high or low churn probability. This helps the organization identify customers who are likely to disengage and take preventive actions through targeted strategies.


3. State-Level Analysis

The system aggregates data at the state level to enable regional insights. For each state, it computes:

Current performance metrics

Predicted outcomes

Customer risk distribution

Operational indicators

This allows the organization to understand variations across different geographic regions.

4. KPI Generation

Key performance indicators are calculated to evaluate business performance, including:

Revenue trends

Marketing effectiveness

Customer engagement

Inventory efficiency

These KPIs provide a structured way to monitor and compare performance across states.

5. Decision Support Logic

The system incorporates rule-based logic to convert insights into actionable recommendations. Based on model outputs and KPIs, it suggests actions such as:

Increasing marketing efforts in high-growth regions

Optimizing inventory in overstocked areas

Focusing on customer retention in high-risk segments

This transforms the system from a reporting tool into a decision support system.

6. Data Export for Dashboard Integration

The final processed dataset, including predictions and KPIs, is exported in a structured format. This dataset is then used in Power BI to create an interactive dashboard.

## System Value

The overall system enables the organization to:


Transition from reactive to predictive decision-making
Understand business performance at a granular, state level
Integrate AI-driven insights into business workflows
Improve operational efficiency and strategic planning


##Conclusion

This project demonstrates how machine learning and data analytics can be integrated into a unified system to support real-world business decisions. By combining data processing, predictive modeling, and structured outputs, the system provides a strong foundation for building interactive, insight-driven dashboards and enabling intelligent decision-making across regions.
"""

# Install required libraries
# Run this only once in Colab

!pip install pandas numpy scikit-learn matplotlib openpyxl --quiet

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt

# Create synthetic India-level business dataset

import pandas as pd
import numpy as np

np.random.seed(42)

states = [
    "Maharashtra", "Delhi", "Karnataka", "Tamil Nadu", "Uttar Pradesh",
    "Gujarat", "West Bengal", "Rajasthan", "Punjab", "Haryana"
]

n = 2000

data = {
    "state": np.random.choice(states, n),
    "units_sold": np.random.randint(10, 500, n),
    "unit_price": np.random.randint(100, 2000, n),
    "marketing_spend": np.random.randint(5000, 50000, n),
    "inventory_available": np.random.randint(50, 1000, n),
    "customer_count": np.random.randint(1, 20, n),
    "last_purchase_days": np.random.randint(1, 120, n),
    "purchase_frequency": np.random.randint(1, 10, n)
}

df = pd.DataFrame(data)

# Create revenue
df["revenue"] = df["units_sold"] * df["unit_price"]

df.head()

# Check dataset size and column names

print("Shape of dataset:", df.shape)
print("\nColumns in dataset:")
print(df.columns.tolist())

# Inspect missing values and data types

print("Missing values:\n")
print(df.isnull().sum())

print("\nData types:\n")
print(df.dtypes)

# Remove duplicate rows if any

df = df.drop_duplicates()

# Reset index after removing duplicates
df = df.reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

# Create derived columns useful for business decision-making
# These are examples; adjust names according to your dataset

# Example: total revenue
if {"units_sold", "unit_price"}.issubset(df.columns):
    df["revenue"] = df["units_sold"] * df["unit_price"]

# Example: marketing ROI proxy
if {"revenue", "marketing_spend"}.issubset(df.columns):
    df["marketing_roi"] = (df["revenue"] - df["marketing_spend"]) / df["marketing_spend"]

# Example: inventory gap
if {"predicted_demand", "inventory_available"}.issubset(df.columns):
    df["inventory_gap"] = df["inventory_available"] - df["predicted_demand"]

df.head()

# Check number of records by state

if "state" in df.columns:
    state_summary = df["state"].value_counts().reset_index()
    state_summary.columns = ["state", "record_count"]
    print(state_summary.head(20))
else:
    print("Column 'state' not found in dataset.")

# Create state-level summary for dashboard insights

group_cols = []
if "state" in df.columns:
    group_cols.append("state")

agg_dict = {}

for col in ["revenue", "marketing_spend", "units_sold", "inventory_available", "customer_count"]:
    if col in df.columns:
        agg_dict[col] = "sum"

if group_cols and agg_dict:
    state_business_summary = df.groupby(group_cols).agg(agg_dict).reset_index()
    display(state_business_summary.head())
else:
    print("Required grouping columns or metrics not found.")

# Define target variable for regression model
# Here we assume revenue prediction as business target

target_column = "revenue"

if target_column not in df.columns:
    raise ValueError(f"Target column '{target_column}' not found in dataset.")

print("Target column selected:", target_column)

# Select relevant features for model building
# Remove identifiers and target from feature list

drop_columns = [target_column]

for col in ["customer_id", "order_id", "transaction_id"]:
    if col in df.columns:
        drop_columns.append(col)

X = df.drop(columns=drop_columns, errors="ignore")
y = df[target_column]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

# Identify categorical and numerical features

categorical_features = X.select_dtypes(include=["object"]).columns.tolist()
numerical_features = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

# Build preprocessing pipeline for missing values and encoding/scaling

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", SimpleImputer(strategy="most_frequent"))
])

# Note:
# For RandomForest, scaling is not mandatory, but keeping it makes workflow reusable.

# Build full preprocessor using one-hot encoding for categorical columns

from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

print("Preprocessor ready.")

# Split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

# Create machine learning pipeline for revenue prediction

revenue_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        max_depth=10,
        random_state=42,
        n_jobs=-1
    ))
])

print("Revenue prediction pipeline created.")

# Train the revenue prediction model

revenue_model.fit(X_train, y_train)

print("Model training completed successfully.")

# Generate predictions on unseen test data

y_pred = revenue_model.predict(X_test)

# Preview a few predictions
prediction_preview = pd.DataFrame({
    "actual_revenue": y_test.values[:10],
    "predicted_revenue": y_pred[:10]
})

prediction_preview

# Evaluate model performance using standard regression metrics

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Model Evaluation Results")
print("------------------------")
print("MAE :", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R2  :", round(r2, 4))

# Optional: Create a churn-risk label for business decision support
# Adjust logic according to your dataset

if {"last_purchase_days", "purchase_frequency"}.issubset(df.columns):
    df["churn_risk"] = np.where(
        (df["last_purchase_days"] > 60) & (df["purchase_frequency"] < 3),
        "High",
        "Low"
    )
    print(df["churn_risk"].value_counts())
else:
    print("Columns required for churn_risk creation not found. Skipping this step.")

# Prepare classification dataset for churn prediction if churn_risk exists

if "churn_risk" in df.columns:
    X_class = df.drop(columns=["churn_risk"], errors="ignore")
    y_class = df["churn_risk"]

    # Remove IDs if present
    for col in ["customer_id", "order_id", "transaction_id"]:
        if col in X_class.columns:
            X_class = X_class.drop(columns=[col])

    print("Classification dataset ready.")
    print("Feature shape:", X_class.shape)
else:
    print("churn_risk column not found. Skipping classification dataset step.")

# Train-test split for classification model

if "churn_risk" in df.columns:
    Xc_train, Xc_test, yc_train, yc_test = train_test_split(
        X_class, y_class, test_size=0.2, random_state=42, stratify=y_class
    )

    print("Classification train shape:", Xc_train.shape)
    print("Classification test shape:", Xc_test.shape)
else:
    print("Skipping because churn_risk does not exist.")

# Separate feature types for classification dataset

if "churn_risk" in df.columns:
    cat_features_class = Xc_train.select_dtypes(include=["object"]).columns.tolist()
    num_features_class = Xc_train.select_dtypes(exclude=["object"]).columns.tolist()

    print("Categorical features:", cat_features_class)
    print("Numerical features:", num_features_class)
else:
    print("Skipping because churn_risk does not exist.")

# Build preprocessing pipeline for classification model

if "churn_risk" in df.columns:
    preprocessor_class = ColumnTransformer(
        transformers=[
            ("num", Pipeline(steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ]), num_features_class),
            ("cat", Pipeline(steps=[
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(handle_unknown="ignore"))
            ]), cat_features_class)
        ]
    )

    print("Classification preprocessor ready.")
else:
    print("Skipping because churn_risk does not exist.")

# Create churn prediction model pipeline

if "churn_risk" in df.columns:
    churn_model = Pipeline(steps=[
        ("preprocessor", preprocessor_class),
        ("model", RandomForestClassifier(
            n_estimators=200,
            max_depth=10,
            random_state=42,
            n_jobs=-1
        ))
    ])

    print("Churn model pipeline created.")
else:
    print("Skipping because churn_risk does not exist.")

# Train churn classification model

if "churn_risk" in df.columns:
    churn_model.fit(Xc_train, yc_train)
    print("Churn model training completed.")
else:
    print("Skipping because churn_risk does not exist.")

# Evaluate churn classification model

if "churn_risk" in df.columns:
    yc_pred = churn_model.predict(Xc_test)

    print("Accuracy:", round(accuracy_score(yc_test, yc_pred), 4))
    print("\nClassification Report:\n")
    print(classification_report(yc_test, yc_pred))
else:
    print("Skipping because churn_risk does not exist.")

# Add revenue prediction to full dataset for dashboard use

df["predicted_revenue"] = revenue_model.predict(X)

df[["predicted_revenue"]].head()

# Add churn predictions if churn model exists

if "churn_risk" in df.columns:
    df["predicted_churn_risk"] = churn_model.predict(X_class)

    print(df["predicted_churn_risk"].value_counts())
else:
    print("Skipping because churn model not available.")

# Create dashboard-ready state-level summary table

dashboard_group = ["state"] if "state" in df.columns else []

dashboard_metrics = {}

for col in ["revenue", "predicted_revenue", "marketing_spend", "units_sold", "inventory_available"]:
    if col in df.columns:
        dashboard_metrics[col] = "sum"

if "customer_id" in df.columns:
    dashboard_metrics["customer_id"] = "nunique"

dashboard_df = df.groupby(dashboard_group).agg(dashboard_metrics).reset_index()

if "customer_id" in dashboard_df.columns:
    dashboard_df = dashboard_df.rename(columns={"customer_id": "unique_customers"})

dashboard_df.head()

# Create derived KPIs for dashboard storytelling

if {"revenue", "marketing_spend"}.issubset(dashboard_df.columns):
    dashboard_df["marketing_roi"] = (
        (dashboard_df["revenue"] - dashboard_df["marketing_spend"]) /
        dashboard_df["marketing_spend"]
    ).replace([np.inf, -np.inf], np.nan)

if {"revenue", "unique_customers"}.issubset(dashboard_df.columns):
    dashboard_df["revenue_per_customer"] = dashboard_df["revenue"] / dashboard_df["unique_customers"]

if {"inventory_available", "units_sold"}.issubset(dashboard_df.columns):
    dashboard_df["inventory_turnover_proxy"] = dashboard_df["units_sold"] / dashboard_df["inventory_available"]

dashboard_df.head()

# Add churn-risk counts by state if available

if {"state", "predicted_churn_risk"}.issubset(df.columns):
    churn_summary = (
        df.groupby(["state", "predicted_churn_risk"])
        .size()
        .unstack(fill_value=0)
        .reset_index()
    )

    dashboard_df = dashboard_df.merge(churn_summary, on="state", how="left")
    dashboard_df.head()
else:
    print("Skipping churn summary merge because required columns are not available.")

# Create simple business recommendation logic for state-wise decision support

def recommendation_engine(row):
    recommendations = []

    if "marketing_roi" in row and pd.notna(row["marketing_roi"]):
        if row["marketing_roi"] < 0.10:
            recommendations.append("Review marketing spend")
        else:
            recommendations.append("Scale winning campaigns")

    if "predicted_revenue" in row and "revenue" in row:
        if row["predicted_revenue"] > row["revenue"]:
            recommendations.append("Prepare for growth")
        else:
            recommendations.append("Stabilize performance")

    if "inventory_turnover_proxy" in row and pd.notna(row["inventory_turnover_proxy"]):
        if row["inventory_turnover_proxy"] < 0.5:
            recommendations.append("Reduce excess inventory")
        else:
            recommendations.append("Maintain stock flow")

    return " | ".join(recommendations)

dashboard_df["decision_recommendation"] = dashboard_df.apply(recommendation_engine, axis=1)

dashboard_df[["state", "decision_recommendation"]].head()

# Power BI map works better when geo fields are clean
# Standardize state names if required

dashboard_df["state"] = dashboard_df["state"].astype(str).str.strip()

print("Unique state values:")
print(sorted(dashboard_df["state"].unique())[:20])

# Save final dashboard dataset for Power BI

dashboard_df.to_csv("powerbi_ready_dataset.csv", index=False)

print("File saved successfully: powerbi_ready_dataset.csv")

import numpy as np
import pandas as pd

# =========================================================
# STEP 1: Start from your main cleaned dataset
# Replace df with your actual dataframe name if different
# =========================================================

# Example:
# df = sales_df.copy()

# Make a copy
dashboard_df = df.copy()

# =========================================================
# STEP 2: Ensure required base columns exist
# If some columns are missing in your dataset, create them
# =========================================================

# state
if 'state' not in dashboard_df.columns:
    dashboard_df['state'] = 'Unknown'

# revenue
if 'revenue' not in dashboard_df.columns:
    # Example fallback: units_sold * selling_price
    if 'units_sold' in dashboard_df.columns and 'price_per_unit' in dashboard_df.columns:
        dashboard_df['revenue'] = dashboard_df['units_sold'] * dashboard_df['price_per_unit']
    else:
        dashboard_df['revenue'] = 0

# predicted_revenue
if 'predicted_revenue' not in dashboard_df.columns:
    # Example: predicted as 8% above current revenue
    dashboard_df['predicted_revenue'] = dashboard_df['revenue'] * 1.08

# marketing_spend
if 'marketing_spend' not in dashboard_df.columns:
    dashboard_df['marketing_spend'] = dashboard_df['revenue'] * 0.12   # example assumption

# marketing_roi
if 'marketing_roi' not in dashboard_df.columns:
    dashboard_df['marketing_roi'] = np.where(
        dashboard_df['marketing_spend'] > 0,
        (dashboard_df['revenue'] - dashboard_df['marketing_spend']) / dashboard_df['marketing_spend'],
        0
    )

# units_sold
if 'units_sold' not in dashboard_df.columns:
    if 'revenue' in dashboard_df.columns and 'price_per_unit' in dashboard_df.columns:
        dashboard_df['units_sold'] = dashboard_df['revenue'] / dashboard_df['price_per_unit']
    else:
        dashboard_df['units_sold'] = 0

# inventory_available
if 'inventory_available' not in dashboard_df.columns:
    dashboard_df['inventory_available'] = np.random.randint(50, 500, size=len(dashboard_df))

# inventory_turnover_proxy
if 'inventory_turnover_proxy' not in dashboard_df.columns:
    dashboard_df['inventory_turnover_proxy'] = np.where(
        dashboard_df['inventory_available'] > 0,
        dashboard_df['units_sold'] / dashboard_df['inventory_available'],
        0
    )

# unique_customers
if 'unique_customers' not in dashboard_df.columns:
    if 'customer_id' in dashboard_df.columns:
        # if row-level data exists, this will be fixed later in grouped summary
        dashboard_df['unique_customers'] = 1
    else:
        dashboard_df['unique_customers'] = np.random.randint(20, 200, size=len(dashboard_df))

# predicted_churn_risk
if 'predicted_churn_risk' not in dashboard_df.columns:
    # Example churn logic
    dashboard_df['predicted_churn_risk'] = np.where(
        dashboard_df['marketing_roi'] < 1, 'High',
        np.where(dashboard_df['marketing_roi'] < 2, 'Medium', 'Low')
    )

# decision_recommendation
if 'decision_recommendation' not in dashboard_df.columns:
    def get_decision(row):
        if row['predicted_churn_risk'] == 'High' and row['inventory_turnover_proxy'] < 0.5:
            return 'Improve retention and optimize inventory'
        elif row['marketing_roi'] < 1:
            return 'Review marketing spend efficiency'
        elif row['predicted_revenue'] > row['revenue']:
            return 'Increase sales efforts and stock planning'
        else:
            return 'Maintain current strategy'

        return 'Monitor performance'

    dashboard_df['decision_recommendation'] = dashboard_df.apply(get_decision, axis=1)

# =========================================================
# STEP 3: If your data has multiple rows per state,
# aggregate to one row per state for Power BI
# =========================================================

if dashboard_df['state'].nunique() < len(dashboard_df):
    agg_dict = {
        'revenue': 'sum',
        'predicted_revenue': 'sum',
        'marketing_spend': 'sum',
        'marketing_roi': 'mean',
        'units_sold': 'sum',
        'inventory_available': 'sum',
        'inventory_turnover_proxy': 'mean',
        'unique_customers': 'sum'
    }

    state_summary = dashboard_df.groupby('state', as_index=False).agg(agg_dict)

    # churn summary by dominant category
    churn_mode = dashboard_df.groupby('state')['predicted_churn_risk'].agg(
        lambda x: x.mode().iloc[0] if not x.mode().empty else 'Unknown'
    ).reset_index()

    # recommendation summary by first / most frequent
    recommendation_mode = dashboard_df.groupby('state')['decision_recommendation'].agg(
        lambda x: x.mode().iloc[0] if not x.mode().empty else 'Monitor performance'
    ).reset_index()

    dashboard_df = state_summary.merge(churn_mode, on='state', how='left')
    dashboard_df = dashboard_df.merge(recommendation_mode, on='state', how='left')

# =========================================================
# STEP 4: Keep only required final columns in exact order
# =========================================================

final_columns = [
    'state',
    'revenue',
    'predicted_revenue',
    'marketing_spend',
    'marketing_roi',
    'units_sold',
    'inventory_available',
    'inventory_turnover_proxy',
    'unique_customers',
    'predicted_churn_risk',
    'decision_recommendation'
]

dashboard_df = dashboard_df[final_columns]

# =========================================================
# STEP 5: Save final Power BI file
# =========================================================

dashboard_df.to_csv("powerbi_ready_dataset.csv", index=False)
print("File saved successfully: powerbi_ready_dataset.csv")
print(dashboard_df.head())

from google.colab import files
files.download("powerbi_ready_dataset.csv")

# Quick visualization in Colab before moving to Power BI

if {"state", "revenue"}.issubset(dashboard_df.columns):
    plot_df = dashboard_df.sort_values("revenue", ascending=False).head(10)

    plt.figure(figsize=(12, 6))
    plt.bar(plot_df["state"], plot_df["revenue"])
    plt.xticks(rotation=45)
    plt.title("Top 10 States by Revenue")
    plt.xlabel("State")
    plt.ylabel("Revenue")
    plt.tight_layout()
    plt.show()
else:
    print("Columns needed for plot not found.")

# Visual comparison of actual vs predicted revenue

if {"revenue", "predicted_revenue"}.issubset(dashboard_df.columns):
    plot_df = dashboard_df.sort_values("revenue", ascending=False).head(10)

    x = np.arange(len(plot_df))
    width = 0.35

    plt.figure(figsize=(12, 6))
    plt.bar(x - width/2, plot_df["revenue"], width, label="Actual Revenue")
    plt.bar(x + width/2, plot_df["predicted_revenue"], width, label="Predicted Revenue")

    plt.xticks(x, plot_df["state"], rotation=45)
    plt.title("Actual vs Predicted Revenue by State")
    plt.xlabel("State")
    plt.ylabel("Revenue")
    plt.legend()
    plt.tight_layout()
    plt.show()
else:
    print("Columns needed for plot not found.")

# Final executive summary for notebook closure

print("Project Summary")
print("---------------")
print("1. Cleaned and processed raw business data")
print("2. Built predictive model for revenue forecasting")
print("3. Built optional churn-risk prediction model")
print("4. Created state-level KPI dataset")
print("5. Generated business recommendations")
print("6. Exported Power BI-ready dataset for interactive dashboard")

